apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: salieri20/to-do:5ae7ab471c2513d62064a73220ac089ee816a7f9
          ports:
            - containerPort: 3000
          env:
            - name: mongoDbUrl
              value: mongodb://mongodb:27017/mydb
              
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 32001
